name: EPG Merger
on:
  schedule:
    - cron: '0 0,6,12,18 * * *' # 每6小时跑一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requests
        run: pip install requests
      - name: Run Merge
        run: python merge.py
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
